//
// Created by ECanDo on 2025-08-23.
//

#include "piece.h"

#include <cstring>

int16_t PIECE_VALUE_LUT[BLACK_KING + 1] = {};

void initPieceLUTs() {
	memset(PIECE_VALUE_LUT, 0, sizeof(PIECE_VALUE_LUT));
	PIECE_VALUE_LUT[WHITE_PAWN] = 100;
	PIECE_VALUE_LUT[BLACK_PAWN] = -100;
	PIECE_VALUE_LUT[TYPE_PAWN] = 100;

	PIECE_VALUE_LUT[WHITE_KNIGHT] = 310;
	PIECE_VALUE_LUT[BLACK_KNIGHT] = -310;
	PIECE_VALUE_LUT[TYPE_KNIGHT] = 310;

	PIECE_VALUE_LUT[WHITE_BISHOP] = 330;
	PIECE_VALUE_LUT[BLACK_BISHOP] = -330;
	PIECE_VALUE_LUT[TYPE_BISHOP] = 330;

	PIECE_VALUE_LUT[WHITE_ROOK] = 500;
	PIECE_VALUE_LUT[BLACK_ROOK] = -500;
	PIECE_VALUE_LUT[TYPE_ROOK] = 500;

	PIECE_VALUE_LUT[WHITE_QUEEN] = 950;
	PIECE_VALUE_LUT[BLACK_QUEEN] = -950;
	PIECE_VALUE_LUT[TYPE_QUEEN] = 950;
}

int getPieceValueType(const PieceType piece) {
	return PIECE_VALUE_LUT[piece];
}

int getPieceValue(const Piece piece) {
	return PIECE_VALUE_LUT[piece];
}
